 <?php

 /*
  * Implement hook_menu
  */

 function dpldev_card_menu() {
     $items = array();
     $items['khachhang/cho'] = array(
         'title' => t('Khách hàng Silver ', array(), 'vi'),
         'page callback' => 'dpldev_card_wait',
         'access arguments' => array('access content'),
         'type' => MENU_CALLBACK,
     );
     $items['khachhang/cho/vang'] = array(
         'title' => t('Khách hàng Gold', array(), 'vi'),
         'page callback' => 'dpldev_card_wait',
         'page arguments' => array(2),
         'access arguments' => array('access content'),
         'type' => MENU_CALLBACK,
     );
     $items['khachhang/cho/bachkim'] = array(
         'title' => t('Khách hàng Platinum', array(), 'vi'),
         'page callback' => 'dpldev_card_wait',
         'page arguments' => array(2),
         'access arguments' => array('access content'),
         'type' => MENU_CALLBACK,
     );
     $items['khachhang/cho/kimuong'] = array(
         'title' => t('Khách hàng Diamond', array(), 'vi'),
         'page callback' => 'dpldev_card_wait',
         'page arguments' => array(2),
         'access arguments' => array('access content'),
         'type' => MENU_CALLBACK,
     );
     return $items;
}

 function dpldev_card_wait($type = null) {
    if(!isset($type))
        $having = ' HAVING doanhso >= 1000000000';
     if($type == 'bac') {
         $having = ' HAVING doanhso >= 1000000000 AND doanhso < 2000000000';
     }
     if($type == 'vang')
         $having = ' HAVING doanhso >= 2000000000 AND doanhso < 4000000000';
     if($type == 'bachkim')
         $having = ' HAVING doanhso >= 4000000000 AND doanhso < 6000000000';
     if($type == 'kimcuong')
         $having = ' HAVING doanhso >= 6000000000';

    $sqlcount = "SELECT COUNT(DISTINCT ctd.field_khachhang_nid_value) FROM {content_type_donhang} ctd INNER JOIN content_type_khachhang ctk ON ctk.vid = ctd.field_khachhang_nid_value and ctk.field_khoangoai_value = ctk.nid AND (ctk.field_khachhang_buon_value IS NULL OR ctk.field_khachhang_buon_value = '0')  ";

    $sqlselect = "SELECT ctk.* , SUM(ctd.field_giaban_value*ctd.field_soluong_value - ctd.field_giamgia_value) doanhso, max(ctd.field_ngayban_value) ngayban FROM {content_type_donhang ctd} INNER JOIN content_type_khachhang ctk ON ctk.vid = ctd.field_khachhang_nid_value and ctk.field_khoangoai_value = ctk.nid AND (ctk.field_khachhang_buon_value IS NULL OR ctk.field_khachhang_buon_value = '0') GROUP BY ctd.field_khachhang_nid_value ". $having;
     $result = pager_query($sqlselect, 15, 0, $sqlcount);
     $i = 1;
     while($obj = db_fetch_object($result)) {
         $row['TT'] = $i;
         $row['hovaten'] =  $obj->field_hovaten_value;
         $row['gioitinh'] = $obj ->field_gioitinh_value;
         $row['sdt'] = $obj -> field_mobile_value;
         $row['address'] = $obj -> field_diachi_value;
         $row['hangthe'] = dpldev_card_type($obj -> doanhso);
         $row['doanhso'] = round(($obj -> doanhso)/1000000,2);
         $i++;
         $rows[] = $row;
     }
     $header = array();
     $header['TT'] = array('data' => 'TT', 'class' => 'TT_cho');
     $header['hoten'] =  t('Họ tên', array(), 'vi');
     $header['sex'] =  array('data' => 'Giới tính', 'class' => 'sex_cho');
     $header['SDT'] =  t('Số ĐT', array(), 'vi');
     $header['address'] =  t('Địa chỉ', array(), 'vi');
     $header['hangthe'] =   array('data' => 'Hạng thẻ', 'class' => 'sex_cho');
     $header['doanhso'] =  array('data' => 'Doanh số', 'class' => 'ds_cho');

     $output = theme('table', $header, $rows, array('class' => 'table'));
     $output .= theme('pager');
     return $output;
 }

function dpldev_card_type($value) {
  $hang = '-';
  if($value >= 1000000000 && $value < 2000000000)
    $hang = 'Silver...';
  if($value >= 2000000000 && $value < 4000000000)
    $hang = 'Gold...';
  if($value >= 4000000000 && $value < 6000000000)
    $hang = 'Platinum...';
  if($value >= 6000000000)
    $hang = 'Diamond...';
  return $hang;
}
