 <?php

 /*
  * Implement hook_menu
  */

 function dpldev_card_menu() {
     $items = array();
     $items['khachhang/cho'] = array(
         'title' => t('Khách hàng Silver ', array(), 'vi'),
         'page callback' => 'dpldev_card_wait',
         'access arguments' => array('access content'),
         'type' => MENU_CALLBACK,
     );
     $items['khachhang/cho/vang'] = array(
         'title' => t('Khách hàng Gold', array(), 'vi'),
         'page callback' => 'dpldev_card_wait',
         'page arguments' => array(2),
         'access arguments' => array('access content'),
         'type' => MENU_CALLBACK,
     );
     $items['khachhang/cho/bachkim'] = array(
         'title' => t('Khách hàng Platinum', array(), 'vi'),
         'page callback' => 'dpldev_card_wait',
         'page arguments' => array(2),
         'access arguments' => array('access content'),
         'type' => MENU_CALLBACK,
     );
     $items['khachhang/cho/kimuong'] = array(
         'title' => t('Khách hàng Diamond', array(), 'vi'),
         'page callback' => 'dpldev_card_wait',
         'page arguments' => array(2),
         'access arguments' => array('access content'),
         'type' => MENU_CALLBACK,
     );
     return $items;
}

 function dpldev_card_wait($type = null) {
    if(!isset($type)) {
        $having = ' HAVING doanhso >= 10000000';
        $dk  = '';
    }
    if($type == 'bac') {
        $having = ' HAVING doanhso >= 10000000 AND doanhso < 200000000';
        $dk  = ' AND (hangthe < 2222 OR hangthe IS NULL) ';

     }
     if($type == 'vang') {
        $having = ' HAVING doanhso >= 200000000 AND doanhso < 500000000';
        $dk  = ' AND (hangthe < 4444 OR hangthe IS NULL)';
     }
     if($type == 'bachkim') {
         $having = ' HAVING doanhso >= 500000000 AND doanhso < 1000000000';
         $dk  = ' AND (hangthe < 6666 OR hangthe IS NULL)';
     }
     if($type == 'kimcuong') {
         $having = ' HAVING doanhso >= 1000000000';
         $dk  = ' AND (hangthe < 8888 OR hangthe IS NULL)';
     }

    $sqlcount = "SELECT COUNT(DISTINCT ctd.field_khachhang_nid_value) FROM {content_type_donhang} ctd INNER JOIN content_type_khachhang ctk ON ctk.nid = ctd.field_khachhang_nid_value  ";

    $sqlselect = "SELECT ctk.nid,
                         ctk.field_hovaten_value,
                         MAX(ctk.field_hangthe_value) as hangthe,
                         ctk.field_gioitinh_value,
                         ctk.field_mobile_value,
                         ctk.field_diachi_value,
                         SUM(ctd.field_giaban_value - ctd.field_giamgia_value) doanhso
                   FROM {content_type_donhang} ctd INNER JOIN content_type_khachhang ctk ON ctk.nid = ctd.field_khachhang_nid_value  GROUP BY ctd.field_khachhang_nid_value ".$having . $dk;
     $result = pager_query($sqlselect, 15, 0, $sqlcount);
     $i = 1;
     while($obj = db_fetch_object($result)) {
         $row['TT'] = $i;
         $row['hovaten'] =  $obj->field_hovaten_value;
         $row['gioitinh'] = $obj ->field_gioitinh_value;
         $row['sdt'] = $obj -> field_mobile_value;
         $row['address'] = $obj -> field_diachi_value;
         $row['hangthe'] = dpldev_card_type($obj -> doanhso);
         $row['doanhso'] = round(($obj -> doanhso)/1000000,2);
         $i++;
         $rows[] = $row;
     }
     $header = array();
     $header['TT'] = array('data' => 'TT', 'class' => 'TT_cho');
     $header['hoten'] =  t('Họ tên', array(), 'vi');
     $header['sex'] =  array('data' => 'Giới tính', 'class' => 'sex_cho');
     $header['SDT'] =  t('Số ĐT', array(), 'vi');
     $header['address'] =  t('Địa chỉ', array(), 'vi');
     $header['hangthe'] =   array('data' => 'Hạng thẻ', 'class' => 'sex_cho');
     $header['doanhso'] =  array('data' => 'Doanh số', 'class' => 'ds_cho');

     $output = theme('table', $header, $rows, array('class' => 'table'));
     $output .= theme('pager');
     return $output;
 }

function dpldev_card_type($value) {
  $hang = '-';
  if($value >= 10000000 && $value < 200000000)
    $hang = 'Silver...';
  if($value >= 200000000 && $value < 500000000)
    $hang = 'Gold...';
  if($value >= 500000000 && $value < 1000000000)
    $hang = 'Platinum...';
  if($value >= 1000000000)
    $hang = 'Diamond...';
  return $hang;
}
